### ISSUE TITLE
(css *ClientSessionState) ServerCertificates() panic

### ISSUE THREAD

**Issue by g0rbe** [refraction-networking/utls#105]
Hi!

Go version: `go version go1.18.1 linux/amd64`

Full code:

```go
config := tls.Config{ServerName: "example.com"}
	dialConn, err := net.DialTimeout("tcp", "example.com:443", 2*time.Second)
	if err != nil {
		fmt.Printf("net.DialTimeout error: %+v", err)
		return
	}
	uTlsConn := tls.UClient(dialConn, &config, tls.HelloCustom)
	defer uTlsConn.Close()

	// do not use this particular spec in production
	// make sure to generate a separate copy of ClientHelloSpec for every connection
	spec := tls.ClientHelloSpec{
		TLSVersMax: tls.VersionTLS13,
		TLSVersMin: tls.VersionTLS10,
		CipherSuites: []uint16{
			tls.TLS_AES_256_GCM_SHA384, // tls 1.3
		},
		Extensions: []tls.TLSExtension{
			&tls.SNIExtension{},
			&tls.SupportedCurvesExtension{Curves: []tls.CurveID{tls.X25519, tls.CurveP256, tls.CurveP384, tls.CurveP521}},
			&tls.SupportedPointsExtension{SupportedPoints: []byte{0}}, // uncompressed
			&tls.SessionTicketExtension{},
			&tls.SignatureAlgorithmsExtension{SupportedSignatureAlgorithms: []tls.SignatureScheme{
				tls.ECDSAWithP256AndSHA256,
				tls.ECDSAWithP384AndSHA384,
				tls.ECDSAWithP521AndSHA512,
				tls.PSSWithSHA256,
				tls.PSSWithSHA384,
				tls.PSSWithSHA512,
				tls.PKCS1WithSHA256,
				tls.PKCS1WithSHA384,
				tls.PKCS1WithSHA512,
				tls.ECDSAWithSHA1,
				tls.PKCS1WithSHA1}},
			&tls.KeyShareExtension{[]tls.KeyShare{{Group: tls.X25519}}},
			//&tls.PSKKeyExchangeModesExtension{[]uint8{1}}, // pskModeDHE
			&tls.SupportedVersionsExtension{[]uint16{tls.VersionTLS13}},
		},
		GetSessionID: nil,
	}

	err = uTlsConn.ApplyPreset(&spec)

	if err != nil {
		fmt.Printf("uTlsConn.Handshake() error: %+v", err)
		return
	}

	err = uTlsConn.Handshake()
	if err != nil {
		fmt.Printf("uTlsConn.Handshake() error: %+v", err)
		return
	}

	uTlsConn.HandshakeState.Session.ServerCertificates()
```

The ServerCertificate() always panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5cfa02]

goroutine 1 [running]:
github.com/refraction-networking/utls.(*ClientSessionState).ServerCertificates(...)
	/home/X/go/pkg/mod/github.com/refraction-networking/utls@v1.1.0/u_public.go:599
main.main()
	/home/X/X/X/testtls/main.go:67 +0x882
exit status 2
```

( I rewrite the host to example.com, but panics with example.com too)

**Comment by g0rbe** [comment]
I totally misunderstood the purpose of ClientSessionState.
I want to get the server's certifications.
The solution is in the underlying Conn :)
